import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { TrendingUp, TrendingDown, Activity, AlertCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";

interface Insight {
  id: string;
  type: "increase" | "decrease" | "stable" | "spike";
  category: string;
  message: string;
  severity: "info" | "warning" | "critical";
}

const insights: Insight[] = [
  {
    id: "i1",
    type: "increase",
    category: "Storage",
    message: "Your storage cost is increasing steadily. Up 22.4% over the last 30 days.",
    severity: "warning",
  },
  {
    id: "i2",
    type: "stable",
    category: "Compute",
    message: "Compute usage is stable with consistent utilization around 85-90%.",
    severity: "info",
  },
  {
    id: "i3",
    type: "spike",
    category: "Networking",
    message: "Networking costs saw a significant spike yesterday. Increased by 156%.",
    severity: "critical",
  },
  {
    id: "i4",
    type: "decrease",
    category: "Database",
    message: "Database costs trending downward after optimization. Down 12% this week.",
    severity: "info",
  },
  {
    id: "i5",
    type: "increase",
    category: "Egress",
    message: "Data transfer costs rising due to increased external API calls.",
    severity: "warning",
  },
  {
    id: "i6",
    type: "stable",
    category: "Lambda",
    message: "Serverless functions maintaining efficient execution with no cost anomalies.",
    severity: "info",
  },
];

export const TrendInsights = () => {
  const getIcon = (type: Insight["type"]) => {
    switch (type) {
      case "increase":
        return <TrendingUp className="h-4 w-4 text-destructive" />;
      case "decrease":
        return <TrendingDown className="h-4 w-4 text-accent" />;
      case "spike":
        return <AlertCircle className="h-4 w-4 text-warning" />;
      case "stable":
        return <Activity className="h-4 w-4 text-primary" />;
    }
  };

  const getSeverityColor = (severity: Insight["severity"]) => {
    switch (severity) {
      case "critical":
        return "border-destructive/30 bg-destructive/10";
      case "warning":
        return "border-warning/30 bg-warning/10";
      case "info":
        return "border-primary/30 bg-primary/10";
    }
  };

  const getSeverityBadge = (severity: Insight["severity"]) => {
    switch (severity) {
      case "critical":
        return "bg-destructive/20 text-destructive border-destructive/30";
      case "warning":
        return "bg-warning/20 text-warning border-warning/30";
      case "info":
        return "bg-primary/20 text-primary border-primary/30";
    }
  };

  return (
    <Card className="border-border/50 bg-card/50 backdrop-blur-sm">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Activity className="h-5 w-5 text-primary" />
          AI Trend Insights
        </CardTitle>
        <CardDescription>
          Auto-generated insights analyzing your cloud spending patterns
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-3">
          {insights.map((insight) => (
            <div
              key={insight.id}
              className={`p-4 rounded-lg border transition-all hover:shadow-sm ${getSeverityColor(
                insight.severity
              )}`}
            >
              <div className="flex items-start gap-3">
                <div className="mt-1">{getIcon(insight.type)}</div>
                <div className="flex-1 space-y-2">
                  <div className="flex items-center gap-2 flex-wrap">
                    <Badge variant="outline" className="text-xs">
                      {insight.category}
                    </Badge>
                    <Badge
                      variant="outline"
                      className={`text-xs ${getSeverityBadge(insight.severity)}`}
                    >
                      {insight.severity}
                    </Badge>
                  </div>
                  <p className="text-sm text-foreground leading-relaxed">{insight.message}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-6 p-4 bg-secondary/30 rounded-lg border border-border/30">
          <p className="text-xs text-muted-foreground">
            💡 <span className="font-semibold">AI Analysis Summary:</span> These insights are
            automatically generated by analyzing your cost trends, usage patterns, and anomalies
            over the past 30 days. Focus on critical and warning items first for maximum impact.
          </p>
        </div>
      </CardContent>
    </Card>
  );
};
