import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Mail, Download } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export const WeeklyEmailGenerator = () => {
  const { toast } = useToast();

  const generateEmailContent = () => {
    const date = new Date().toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    return `Subject: Weekly Cloud Cost Report - ${date}

Dear Team,

Here is your weekly cloud cost summary and optimization recommendations:

📊 COST SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total Monthly Cost: $18,432
Weekly Spend: $4,234
Daily Average: $614
Change from Last Week: ↑ 12.5%

💰 TOP EXPENSES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Compute (EC2): $7,234 (39.2%)
2. Storage (S3): $4,123 (22.4%)
3. Database (RDS): $3,456 (18.7%)
4. Network & CDN: $2,189 (11.9%)
5. Other Services: $1,430 (7.8%)

⚠️ COST ANOMALIES DETECTED
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Unusual spike in database costs on Tuesday (+156%)
• Storage growth rate accelerating (22.4% increase)
• 3 idle EC2 instances detected running for 7+ days

🎯 TOP OPTIMIZATION OPPORTUNITIES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Stop Idle EC2 Instances
   Potential Savings: $1,245/month
   Priority: HIGH
   Action: Terminate 3 instances with <5% utilization

2. Rightsize Underutilized Instances
   Potential Savings: $892/month
   Priority: HIGH
   Action: Downsize 5 instances running at <20% capacity

3. Use Reserved Instances
   Potential Savings: $678/month
   Priority: MEDIUM
   Action: Commit to 1-year reserved instances for stable workloads

4. Clean Up Old Snapshots
   Potential Savings: $234/month
   Priority: MEDIUM
   Action: Delete 127 snapshots older than 90 days

📈 COST FORECAST
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Predicted Next Month: $19,531
Expected Increase: ↑ 6.0%
⚠️ Alert: On track to exceed budget by 8 days

💡 RECOMMENDED ACTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✓ Implement auto-shutdown for dev/test environments (Save 60%)
✓ Move infrequently accessed S3 data to Glacier (Save 85%)
✓ Enable S3 Intelligent-Tiering for automatic cost optimization
✓ Review and delete unused Elastic IPs ($58/month savings)

📊 MULTI-CLOUD COMPARISON
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Current (AWS): $18,432
Azure Equivalent: $17,123 (7.1% cheaper)
GCP Equivalent: $16,845 (8.6% cheaper)

Potential Annual Savings by Switching to GCP: $19,044

🔒 BUDGET STATUS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Monthly Budget: $20,000
Current Spend: $18,432 (92.2% used)
Status: ⚠️ Warning - Projected to exceed budget

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💵 TOTAL POTENTIAL SAVINGS: $3,245/month

This report was automatically generated by Cloud Cost Analyzer.
For detailed charts and interactive analysis, visit your dashboard.

Questions? Contact: cloud-ops@company.com

Best regards,
Cloud Cost Optimization Team
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`;
  };

  const downloadEmail = () => {
    const emailContent = generateEmailContent();
    const blob = new Blob([emailContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `weekly-cost-report-${new Date().toISOString().split("T")[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Email Report Generated",
      description: "Weekly cost report downloaded successfully",
    });
  };

  return (
    <Card className="border-border/50 bg-gradient-to-br from-card to-primary/5">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Mail className="h-5 w-5 text-primary" />
          Weekly Cost Email Report
        </CardTitle>
        <CardDescription>
          Generate automated weekly summary emails with insights and recommendations
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="bg-secondary/30 rounded-lg border border-border/30 p-4 space-y-3">
          <h4 className="font-semibold text-foreground text-sm">Email Report Includes:</h4>
          <ul className="space-y-2 text-sm text-muted-foreground">
            <li className="flex items-start gap-2">
              <span className="text-accent mt-0.5">✓</span>
              <span>Cost summary with weekly trends and comparisons</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-accent mt-0.5">✓</span>
              <span>Service-wise breakdown with percentage contributions</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-accent mt-0.5">✓</span>
              <span>Top optimization opportunities with potential savings</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-accent mt-0.5">✓</span>
              <span>Cost anomaly alerts and budget status updates</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-accent mt-0.5">✓</span>
              <span>Multi-cloud pricing comparison and migration insights</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-accent mt-0.5">✓</span>
              <span>AI-powered recommendations and forecasting</span>
            </li>
          </ul>
        </div>

        <div className="bg-accent/10 border border-accent/30 rounded-lg p-4">
          <p className="text-sm text-foreground mb-3">
            📧 Generate a comprehensive weekly email report perfect for sharing with management,
            finance teams, or stakeholders.
          </p>
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <span className="font-semibold text-accent">Pro Tip:</span>
            <span>Schedule this to run automatically every Monday morning</span>
          </div>
        </div>

        <Button
          onClick={downloadEmail}
          className="w-full bg-gradient-to-r from-primary to-accent hover:opacity-90"
          size="lg"
        >
          <Download className="mr-2 h-4 w-4" />
          Download Weekly Report as TXT
        </Button>
      </CardContent>
    </Card>
  );
};
